# Site settings
title: Rayraegah
email: rayraegah@icloud.com
description: "An engineering psychologist"
tagline: "Hello I am Rayraegah"
baseurl: ""
url: "https://rayraegah.com"
bug_report: "https://github.com/rayraegah/rayraegah.github.io/issues"
images_root: "https://rayraegah.com"

# Social
twitter_username: rayraegah
github_username: rayraegah

# Analytics
tracker: UA-138735543-1

# Content license
license_name: >-
  Creative Commons Attribution-ShareAlike 4.0 International License
license_url: http://creativecommons.org/licenses/by-sa/4.0/

# Pagination
per_page: 10
paginate: 10 # should match per_page above
paginate_path: "page:num"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo
  - jekyll-sitemap
  - jekyll-paginate

# Permanent links
permalink: /journal/:title/

# Do not include in build
exclude:
  - .gitignore
  - .editorconfig
  - README.md
  - LICENSE
  - Dockerfile
  - docker-compose.yml
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - build.sh
  - node_modules
  - vendor
